# Use postgres/example user/password credentials
version: '3.1'

services:
  redis:
    image: 'redis'
    restart: always
    ports:
      - '6379:6379'

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chat-llm
    ports:
      - 5433:5432
      